# 正規表現

もし、わかりにくかったら連絡ください。
修正します。

* 文字列のパターンを表現するためのもの

## メタキャラクタ

通常の正規表現で使えるのは、以下のメタキャラクタ

|メタキャラクタ|効果|
|:------------:|:--------------:|
|\.            |任意の一文字|
|*             |0回以上の繰り返し|
|[文字]        |どれか文字にマッチする|
|^             |アンカー、先頭のこと|
|$             |アンカー、末尾のこと|
|\{n,m\}       |n回以上、m回以下の繰り返し|
|\\(...\\)     |\\(と\\)で囲まれた文字列を保存する|
|\\            |エスケープ|

## 拡張メタキャラクタ

拡張正規表現に対応しているもので使用可能。

|拡張メタキャラクタ|効果|通常のメタキャラクタでの表現|
|:------------:|:--------------:|:------------------:|
|+             |1回以上の繰り返し|\\{1,\\} または ..* |
|?             |0回か1回の連続|\\{0,1\\}|
||             |またはの意味(優先度高い)|[...] が一番近いかな|

ただし、使用する言語、ソフトによっては別の拡張メタキャラクタセットを使用可能。

## 使用例 {#grep}

```bash
#vimを探してみる
dpkg -l | grep 'vim'

#前後に任意の文字が0個以上あるもの
dpkg -l | grep '.*vim.*'

#vimのみを探してみる
#前後のスペースを一回以上にしてみる
dpkg -l | grep ' \{1,\}vim \{1,\}'

#こんな感じにも書ける
dpkg -l | grep '  *vim  *'
```

* \\{n,m\\}は、繰り返しを指定する。
    * \\{n,\\}でn回以上の繰り返し
    * \\{,m\\}でm回以下の繰り返し
* .は任意の一文字
* \*は0回以上の繰り返し
    * .\*は任意の一文字の0回以上の繰り返し
    * ..\*で任意の一文字の1回以上の繰り返し
        * 任意の一文字と任意の一文字の0回以上の繰り返し

# Sed {#sed_page}


文字列の置換に便利な言語

## 代表的なコマンド

|コマンド| 効果　|表現|
|:-------:|:---------:|:-------------:
|s        |置換する|/アドレス/s/パターン/置換後のパターン/|
|y        |パターンで指定したものを入れ替える|y/パターン/パターン/|
|p        |表示する|アドレス/p|
|d        |削除    |アドレス/d|

他にも大文字コマンドがあるが、使用方法が難しいので今回は割愛します。

## 使用例 {#sed01}

```bash
#vimをemacsにしてみる
dpkg -l | grep 'vim' | sed -e 's/vim/emacs/'

#Vim vim Vi vi などのすべてをemacsにしてみる
#最後のgrepはemacsをハイライトさせるため
dpkg -l | grep '[Vv][Ii][Mm]*' | sed -e 's/[Vv][Ii][Mm]*/emacs/' | grep 'emacs'

#Vim vim Vi vi だけをemacsにしてみる
dpkg -l | grep '[Vv]im*' | sed -e 's/[Vv]im*/emacs/' | grep 'emacs'
#このやり方だとvideoなども含まれる

#もう一度やりなおす
dpkg -l | grep '[^a-z][Vv]im*[^a-z]' | sed -e 's/[^a-z][Vv]im*[^a-z]/emacs/' | grep 'emacs'
#だいぶ直ったけど、Vi IMprovedはのこったまま

#Vi IMprovedもemacsに変えてみる
dpkg -l | grep '[^a-z][Vv]im*[^a-z]' | sed -e 's/[^a-z][Vv]im*[^a-z]/emacs/' | sed -e 's/Vi IMproved/emacs/' | grep 'emacs'

```

> grepの抽出とsedのパターン指定が重複してるけど、あんまり意味はない  
> 強いて言うなら、sedのアドレス指定を明示的にするため  


```bash
grep '[^a-z][Vv]im*[^a-z]' | sed -e 's/[^a-z][Vv]im*[^a-z]/emacs/'  
sed -e '/[^a-z][Vv]im*[^a-z]/s/[^a-z][Vv]im*[^a-z]/emacs/'  
sed -e '/[^a-z][Vv]im*[^a-z]/s//emacs/'  
```

> すべて等価な表現  

* [Vv]はVとvどっちかにマッチする
* [Mm]\*は(Mとmどっちかにマッチする)の0回以上の繰り返し
* [a-z]はaからzのすべてのうちどれか一つにマッチする
* [^a-z]は(aからzのすべてのうちどれか一つ)とマッチしない

## 使用例2 {#sed02}

```bash
#viなどをemacs単体に変えて表示
dpkg -l | sed -n -e '/..*[^a-z]\([Vv]im*\)[^a-z]..*/s//\1toemacs/p'

```

> sedのオプション -n は自動出力をやめるオプション  
> pコマンドは表示させるオプション  
> pの後ろにスラッシュはいらない  

* `\(文字列\)`で保存できる
* 参照は`\1`,`\2`のように\\の後に数字をつける
    * `\(a\)``\(b\)`のように複数保存した場合、参照は手前から順に1,2,となる
* `\([Vv]im*\)`を保存して参照すると、viとなっている。
    * m\* は0回として保存
